apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: ghcr.io/billmetangmo/bookish-train
    docker:
      cacheFrom:
       - ghcr.io/billmetangmo/bookish-train:latest
  tagPolicy:
    gitCommit: {}
test:
  - image: ghcr.io/billmetangmo/bookish-train
    custom:
      - command: >
          trivy image --exit-code 1 --no-progress --severity HIGH,CRITICAL ghcr.io/billmetangmo/bookish-train
        timeoutSeconds: 60
deploy:
  kubectl: {}